# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 07:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('note', models.TextField(default='', verbose_name='\u5907\u6ce8')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TextField(verbose_name='\u65f6\u95f4\u6bb5')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='wechat.Plan')),
            ],
        ),
    ]
