# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandetail',
            name='ischeck',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5b8c\u6210'),
        ),
    ]
