# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_plandetail_ischeck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2016, 5, 29, 11, 15, 30, 315828), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
